#!bin/sh

echo "CREATE USER IF NOT EXITS $MYSQL_USERNAME;"
echo "CREATE USER IF NOT EXISTS $MYSQL_USERNAME@'%' IDENTIFIED BY '$MYSQL_PASSWORD';"
echo "GRANT ALL ON *.* TO $MYSQL_USERNAME@'%' IDENTIFIED BY '$MYSQL_PASSWORD';"
echo "FLUSH PRIVILEGES;"
mysqld --bootstrap

exec "$@"